### ISSUE TITLE
Dose symmetry does not work as expected

### ISSUE THREAD

**Issue by MohamadHarastani** [rosalindfranklininstitute/parakeet#39]
Hello James,
There seems to be a problem with dose symmetry. The dose damage seems to be always from the leftmost to the rightmost image in the tilt series. I am on the master branch.
Cheers
Mohamad

**Comment by MohamadHarastani** [comment]
A couple more related issues:
1- I noticed that the option `phase_plate: true` does not have have any effect on the output. I examined the Fourier space of the optics output and there is no sign of phase plates in it.
2- I need to simulate the dose damage on a semi-dose symmetric tilting scheme: `[0, -4, -8, 4, 8, -12, -16, 12, 16, ...]`. So I added this to the `angles` parameter in the config. However, I found that the angles did not override the `start_angle`, `step_angle` and `num_images`. So that was not simulated, nor sorted out the dose symmetry.
Here is the config file to reproduce this issue (changed extension to txt to upload of Github).
[config.txt](https://github.com/rosalindfranklininstitute/parakeet/files/10139671/config.txt)

Cheers
Mohamad

**Comment by jmp1985** [comment]
Hi @MohamadHarastani 

I've addressed this second issue so that now you can do the following:
- if you set the scan mode to "dose_symmetric" it will generate a list of angles and execute them in dose symmetric order.
- if you set the scan mode to "manual" the specified angles will be used. 

Regarding the first issue, I've had a quick look and it's not obvious to me what is wrong, so I will have to take a deeper look to figure out what is happening.

Best wishes
James

**Comment by MohamadHarastani** [comment]
All issues reported here are solved :-)
